export const mockUser = {
    id: "user_dormant_42",
    username: "Tyler_V",
    status: "returning", // "new" | "active" | "returning" (dormant reactivation)
    daysSinceLastVisit: 183,
    interestTags: ["valorant", "anime", "lo-fi music", "indie games", "fantasy basketball"],
    gameLibrary: ["Valorant", "League of Legends", "Elden Ring", "Stardew Valley"],
    friendsOnDiscord: 24,
    previousServers: ["server_001", "server_005", "server_009"], // IDs of servers they left
    activeServers: [], // dormant user has no current active servers
    dereEmbeddingVector: "[gaming:0.87, music:0.61, anime:0.74, sports:0.55, tech:0.32]" // display only
};

export const mockServers = [
    // Gaming (5)
    {
        id: "server_001",
        name: "VALORANT Community",
        description: "The largest Valorant community on Discord. Strategy, clips, LFG, coaching.",
        icon: "🎯",
        iconColor: "#FF4655",
        memberCount: 847200,
        onlineCount: 12400,
        category: "Gaming",
        subTags: ["FPS", "Competitive", "Valorant"],
        isBoosted: true,
        isVerified: true,
        personalizedReason: "back",
        reasonLabel: "You were a member 6 months ago",
        friendsInServer: 0,
        matchScore: 0.94,
    },
    {
        id: "server_005",
        name: "League of Legends",
        description: "Official League of Legends community. Patch notes, discussions, eSports.",
        icon: "⚔️",
        iconColor: "#005A82",
        memberCount: 950000,
        onlineCount: 22000,
        category: "Gaming",
        subTags: ["MOBA", "Competitive", "LoL"],
        isBoosted: true,
        isVerified: true,
        personalizedReason: "back",
        reasonLabel: "You were a member 8 months ago",
        friendsInServer: 0,
        matchScore: 0.88,
    },
    {
        id: "server_011",
        name: "Elden Ring Hub",
        description: "Praise the message! Jolly cooperation, lore hunting, and PvP duels.",
        icon: "💍",
        iconColor: "#B5A642",
        memberCount: 420000,
        onlineCount: 8500,
        category: "Gaming",
        subTags: ["RPG", "Co-op", "Soulsborne"],
        isBoosted: true,
        isVerified: false,
        personalizedReason: "friends",
        reasonLabel: "7 of your friends are here",
        friendsInServer: 7,
        matchScore: 0.85,
    },
    {
        id: "server_012",
        name: "Stardew Valley",
        description: "A friendly community for all things Stardew! Share farms, find co-op groups.",
        icon: "🐔",
        iconColor: "#8BC34A",
        memberCount: 380000,
        onlineCount: 4200,
        category: "Gaming",
        subTags: ["Casual", "Farming", "Co-op"],
        isBoosted: true,
        isVerified: true,
        personalizedReason: "interest",
        reasonLabel: "Matches your game library",
        friendsInServer: 1,
        matchScore: 0.91,
    },
    {
        id: "server_013",
        name: "Fantasy Basketball Hub",
        description: "Discuss trades, waiver wire pickups, injuries, and brag about your team in our fantasy hoops community.",
        icon: "🏀",
        iconColor: "#FF9800",
        memberCount: 85000,
        onlineCount: 1500,
        category: "Gaming",
        subTags: ["Sports", "Fantasy", "NBA"],
        isBoosted: true,
        isVerified: false,
        personalizedReason: "trending",
        reasonLabel: "Trending with NBA Season start",
        friendsInServer: 0,
        matchScore: 0.76,
    },

    // Music (2)
    {
        id: "server_002",
        name: "Lo-Fi Café",
        description: "24/7 lo-fi beats to chill/study to. Cozy community for night owls and creators.",
        icon: "☕",
        iconColor: "#8D6E63",
        memberCount: 215000,
        onlineCount: 6800,
        category: "Music",
        subTags: ["Lo-Fi", "Study", "Chill"],
        isBoosted: true,
        isVerified: false,
        personalizedReason: "interest",
        reasonLabel: "Based on your music tags",
        friendsInServer: 2,
        matchScore: 0.82,
    },
    {
        id: "server_014",
        name: "Anime OST Community",
        description: "Discussing our favorite anime soundtracks, composers, and sharing high-res audio.",
        icon: "🎵",
        iconColor: "#E91E63",
        memberCount: 112000,
        onlineCount: 2100,
        category: "Music",
        subTags: ["Anime", "Soundtracks", "Discussion"],
        isBoosted: false,
        isVerified: false,
        personalizedReason: "interest",
        reasonLabel: "You like Anime & Music",
        friendsInServer: 0,
        matchScore: 0.89,
    },

    // Anime (2)
    {
        id: "server_003",
        name: "Anime Universe",
        description: "The biggest hub for anime/manga fans. Episodic discussions and fan art.",
        icon: "🎌",
        iconColor: "#FF7043",
        memberCount: 650000,
        onlineCount: 15400,
        category: "Anime",
        subTags: ["Anime", "Manga", "Art"],
        isBoosted: true,
        isVerified: true,
        personalizedReason: "friends",
        reasonLabel: "3 friends are active here",
        friendsInServer: 3,
        matchScore: 0.81,
    },
    {
        id: "server_009",
        name: "One Piece Community",
        description: "Dedicated to the One Piece manga and anime. Spoilers ahead!",
        icon: "☠️",
        iconColor: "#FFCA28",
        memberCount: 310000,
        onlineCount: 8200,
        category: "Anime",
        subTags: ["Manga", "One Piece", "Discussion"],
        isBoosted: true,
        isVerified: false,
        personalizedReason: "back",
        reasonLabel: "You left 2 months ago",
        friendsInServer: 1,
        matchScore: 0.77,
    },

    // Education/Tech (2)
    {
        id: "server_004",
        name: "AI Builders",
        description: "Developers, researchers, and hobbyists building with the latest AI models.",
        icon: "🤖",
        iconColor: "#42A5F5",
        memberCount: 185000,
        onlineCount: 4500,
        category: "Science & Tech",
        subTags: ["AI", "Programming", "Tech"],
        isBoosted: true,
        isVerified: false,
        personalizedReason: "serendipity",
        reasonLabel: "Explore something new",
        friendsInServer: 0,
        matchScore: 0.35,
    },
    {
        id: "server_015",
        name: "Indie Game Dev",
        description: "A community for indie developers to share progress, get feedback, and collaborate.",
        icon: "👾",
        iconColor: "#AB47BC",
        memberCount: 240000,
        onlineCount: 5600,
        category: "Science & Tech",
        subTags: ["Game Dev", "Programming", "Art"],
        isBoosted: true,
        isVerified: true,
        personalizedReason: "interest",
        reasonLabel: "Based on 'indie games' tag",
        friendsInServer: 0,
        matchScore: 0.86,
    },

    // Entertainment (2)
    {
        id: "server_016",
        name: "NBA Talk",
        description: "Live game threads, trade rumors, and basketball discussion.",
        icon: "🏀",
        iconColor: "#1565C0",
        memberCount: 156000,
        onlineCount: 3200,
        category: "Entertainment",
        subTags: ["Sports", "NBA", "Discussion"],
        isBoosted: false,
        isVerified: false,
        personalizedReason: "friends",
        reasonLabel: "2 friends are here",
        friendsInServer: 2,
        matchScore: 0.65,
    },
    {
        id: "server_017",
        name: "Retro Gaming Lounge",
        description: "Nostalgic gamers discussing retro consoles, speedruns, and game collecting.",
        icon: "🕹️",
        iconColor: "#7E57C2",
        memberCount: 198000,
        onlineCount: 4100,
        category: "Entertainment",
        subTags: ["Gaming", "Retro", "Collecting"],
        isBoosted: true,
        isVerified: false,
        personalizedReason: "trending",
        reasonLabel: "Trending: Retro speedruns",
        friendsInServer: 0,
        matchScore: 0.58,
    }
];
